// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJ_KZTx-JkbaWuhEKu_rbJaogvH9-QTs',
    appId: '1:718327800:web:fd8c5102ef0c2d6bf4100d',
    messagingSenderId: '718327800',
    projectId: 'blood-connect-6183b',
    authDomain: 'blood-connect-6183b.firebaseapp.com',
    storageBucket: 'blood-connect-6183b.firebasestorage.app',
    measurementId: 'G-5MNHGSQ8KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFzDPcGHQ0uRqKA3whB_i0yTmUzdFm0s',
    appId: '1:718327800:android:ca614b07cb09ef29f4100d',
    messagingSenderId: '718327800',
    projectId: 'blood-connect-6183b',
    storageBucket: 'blood-connect-6183b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcHExljQ2ZuR6xHe2xrdN_d0HS87zRnE',
    appId: '1:718327800:ios:d342a6ae980ef5fbf4100d',
    messagingSenderId: '718327800',
    projectId: 'blood-connect-6183b',
    storageBucket: 'blood-connect-6183b.firebasestorage.app',
    androidClientId: '718327800-nkqei4ipj22ampjf9d5jj3a27c91qblr.apps.googleusercontent.com',
    iosClientId: '718327800-62a9pujrbuikmgsp6t1gdko69cgdsq25.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcHExljQ2ZuR6xHe2xrdN_d0HS87zRnE',
    appId: '1:718327800:ios:d342a6ae980ef5fbf4100d',
    messagingSenderId: '718327800',
    projectId: 'blood-connect-6183b',
    storageBucket: 'blood-connect-6183b.firebasestorage.app',
    androidClientId: '718327800-nkqei4ipj22ampjf9d5jj3a27c91qblr.apps.googleusercontent.com',
    iosClientId: '718327800-62a9pujrbuikmgsp6t1gdko69cgdsq25.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQJ_KZTx-JkbaWuhEKu_rbJaogvH9-QTs',
    appId: '1:718327800:web:2d1a3140a1f8d75ef4100d',
    messagingSenderId: '718327800',
    projectId: 'blood-connect-6183b',
    authDomain: 'blood-connect-6183b.firebaseapp.com',
    storageBucket: 'blood-connect-6183b.firebasestorage.app',
    measurementId: 'G-WJSWNM43YM',
  );

}